name: Release libs

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: Release libs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: Release MacOS And Linux lib
      if: runner.os != 'Windows'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/libdeno_installer.so
        tag: ${{ github.ref }}
        overwrite: true

    - name: Release Windows lib
      if: runner.os == 'Windows'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/deno_installer.dll
        tag: ${{ github.ref }}
        overwrite: true